#!/bin/bash -ex

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

echo Setting up Python virtual environment
BUILDDIR="$(pwd)/build"
mkdir -p "${BUILDDIR}"
python3 -m venv "${BUILDDIR}/venv"
. "${BUILDDIR}/venv/bin/activate"

# update pip3
pip3 install --upgrade pip

# aarch64 requires a very new Pyinstaller, but our old centos6 x86_64
# agent breaks with anything newer than 4.2
echo "Install pyinstaller"
if [ `uname -m` != "x86_64" ]; then
    PYINSTALLER_VERSION=4.5.1
else
    PYINSTALLER_VERSION=4.2
fi
pip3 install pyinstaller==${PYINSTALLER_VERSION}

echo Installing cbdep requirements
pip3 install -r ${SCRIPTPATH}/requirements.txt

# Customize _buildversion.py if build info available in environment
if [ ! -z "${VERSION}" -a ! -z "${BLD_NUM}" ]; then
    VERSIONPATH="${BUILDDIR}/version"
    mkdir -p "${VERSIONPATH}"
    cat <<EOF > "${VERSIONPATH}/_buildversion.py"
__version__ = "${VERSION}"
__build__ = "${BLD_NUM}"
EOF
else
    VERSIONPATH=""
fi

echo Compiling cbdep
PYINSTDIR=$(pwd)/build/pyinstaller
mkdir -p ${PYINSTDIR}
pyinstaller --log-level DEBUG \
    --add-data ${SCRIPTPATH}/cbdep.config:. \
    --workpath ${PYINSTDIR} \
    --specpath ${PYINSTDIR} \
    --distpath dist --noconfirm \
    --onefile --clean \
    --paths "${VERSIONPATH}:${SCRIPTPATH}/cbdep/scripts" \
    ${SCRIPTPATH}/cbdep/scripts/cbdep.py
