#!/bin/bash -ex

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

echo Setting up Python virtual environment
mkdir -p build
python3 -m venv build/venv
. build/venv/bin/activate

# update pip3
pip3 install --upgrade pip

# aarch64 requires a very new Pyinstaller, but our old centos6 x86_64
# agent breaks with anything newer than 4.2
echo "Install pyinstaller"
if [ `uname -m` != "x86_64" ]; then
    PYINSTALLER_VERSION=4.5.1
else
    PYINSTALLER_VERSION=4.2
fi
pip3 install pyinstaller==${PYINSTALLER_VERSION}

echo Installing cbdep requirements
pip3 install -r ${SCRIPTPATH}/requirements.txt

echo Compiling cbdep
PYINSTDIR=$(pwd)/build/pyinstaller
mkdir -p ${PYINSTDIR}
pyinstaller --log-level DEBUG \
    --add-data ${SCRIPTPATH}/cbdep.config:. \
    --workpath ${PYINSTDIR} \
    --specpath ${PYINSTDIR} \
    --distpath dist --noconfirm \
    --onefile --clean \
    --paths ${SCRIPTPATH}/cbdep/scripts \
    ${SCRIPTPATH}/cbdep/scripts/cbdep.py
