#!/bin/bash -ex

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

echo Setting up Python virtual environment
mkdir -p build
python3 -m venv build/venv
. build/venv/bin/activate

#update pip3
pip3 install --upgrade pip

# Until https://github.com/pyinstaller/pyinstaller/issues/5315 is closed,
# point to the arm-support branch
echo "Install pyinstaller"
if [ `uname -m` == "arm64" ]; then
    pip3 install https://github.com/couchbasebuild/pyinstaller/archive/refs/heads/macos11-arm64-support-cleanup.zip
else
    pip3 install pyinstaller
fi

echo Installing cbdep requirements
pip3 install -r ${SCRIPTPATH}/requirements.txt

echo Compiling cbdep
PYINSTDIR=$(pwd)/build/pyinstaller
mkdir -p ${PYINSTDIR}
pyinstaller --log-level DEBUG \
    --add-data ${SCRIPTPATH}/cbdep.config:. \
    --workpath ${PYINSTDIR} \
    --specpath ${PYINSTDIR} \
    --distpath dist --noconfirm \
    --onefile --clean \
    --paths ${SCRIPTPATH}/cbdep/scripts \
    ${SCRIPTPATH}/cbdep/scripts/cbdep.py
